name: lint-and-test

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install pep8
    - run: pip3 install pycodestyle
    - name: Run pep8
      run: pycodestyle .
